// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/go-api/app (interfaces: CatApp)

// Package app is a generated GoMock package.
package app

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/viniosilva/go-api/model"
)

// MockCatApp is a mock of CatApp interface.
type MockCatApp struct {
	ctrl     *gomock.Controller
	recorder *MockCatAppMockRecorder
}

// MockCatAppMockRecorder is the mock recorder for MockCatApp.
type MockCatAppMockRecorder struct {
	mock *MockCatApp
}

// NewMockCatApp creates a new mock instance.
func NewMockCatApp(ctrl *gomock.Controller) *MockCatApp {
	mock := &MockCatApp{ctrl: ctrl}
	mock.recorder = &MockCatAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatApp) EXPECT() *MockCatAppMockRecorder {
	return m.recorder
}

// FindCats mocks base method.
func (m *MockCatApp) FindCats() []model.Cat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCats")
	ret0, _ := ret[0].([]model.Cat)
	return ret0
}

// FindCats indicates an expected call of FindCats.
func (mr *MockCatAppMockRecorder) FindCats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCats", reflect.TypeOf((*MockCatApp)(nil).FindCats))
}
