// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/go-api/repository (interfaces: CatRepository)

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/viniosilva/go-api/model"
)

// MockCatRepository is a mock of CatRepository interface.
type MockCatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatRepositoryMockRecorder
}

// MockCatRepositoryMockRecorder is the mock recorder for MockCatRepository.
type MockCatRepositoryMockRecorder struct {
	mock *MockCatRepository
}

// NewMockCatRepository creates a new mock instance.
func NewMockCatRepository(ctrl *gomock.Controller) *MockCatRepository {
	mock := &MockCatRepository{ctrl: ctrl}
	mock.recorder = &MockCatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatRepository) EXPECT() *MockCatRepositoryMockRecorder {
	return m.recorder
}

// FindCats mocks base method.
func (m *MockCatRepository) FindCats() []model.Cat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCats")
	ret0, _ := ret[0].([]model.Cat)
	return ret0
}

// FindCats indicates an expected call of FindCats.
func (mr *MockCatRepositoryMockRecorder) FindCats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCats", reflect.TypeOf((*MockCatRepository)(nil).FindCats))
}
