definitions:
  api.ErrorResponse:
    properties:
      message:
        example: Invalid request
        type: string
    type: object
  api.HealthResponse:
    properties:
      status:
        type: string
    type: object
  cat.CatCmd:
    properties:
      birthday:
        example: "2000-01-01"
        type: string
      name:
        example: Mimoso
        type: string
    type: object
  cat.CatDto:
    properties:
      birthday:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  cat.ListCatsDto:
    properties:
      data:
        items:
          $ref: '#/definitions/cat.CatDto'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/health:
    get:
      description: Healthcheck route
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/api.HealthResponse'
      tags:
      - health
  /api/v1/cats:
    get:
      description: Find cats route
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cat.ListCatsDto'
      tags:
      - cat
    post:
      description: Create cat route
      parameters:
      - description: Cat
        in: body
        name: cat
        required: true
        schema:
          $ref: '#/definitions/cat.CatCmd'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/cat.CatDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - cat
swagger: "2.0"
